#!/usr/bin/env python3
"""
SUN GALLERY — image optimiser
=============================

WHAT IT DOES
  Takes your full-size originals (JPG / PNG / HEIC — straight off the phone
  or camera is fine) and produces the responsive WebP set the website loads,
  then writes assets/js/media.js so the site picks them up automatically.

HOW TO USE
  1. pip install pillow pillow-heif numpy
  2. Put photos in            tools/originals/
     Name each file after the key you want, e.g.  copper-bath.jpg
  3. python3 tools/optimize-images.py
  4. Reference the key in assets/js/data.js:   images: ["copper-bath"]

WHAT YOU GET PER PHOTO
  <key>-400.webp / -800.webp / -1600.webp   (never upscaled, long edge capped)
  plus a dominant colour and a ~600-byte inline blur preview, so every image
  fades up from a matching blur instead of flashing white.

Re-running is safe and idempotent. Keys not regenerated are preserved.
"""
import os, io, json, base64, re
from PIL import Image, ImageFilter
import numpy as np
try:
    from pillow_heif import register_heif_opener; register_heif_opener()
except ImportError:
    pass

ROOT      = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIDTHS    = [400, 800, 1600]
MAX_EDGE  = 2000          # never write anything longer than this on either side
QUALITY   = 74
CATEGORY  = "stones"      # subfolder under assets/img/


def dominant(im):
    """Average of the darker half — matches the blur-up plate to the photo."""
    t = im.copy(); t.thumbnail((64, 64))
    a = np.asarray(t.convert("RGB")).reshape(-1, 3).astype(float)
    lum = a @ [0.299, 0.587, 0.114]
    sel = a[lum <= np.percentile(lum, 58)]
    if not len(sel):
        sel = a
    r, g, b = sel.mean(0).astype(int)
    return "#%02x%02x%02x" % (r, g, b)


def lqip(im):
    """Tiny blurred inline preview (base64 WebP, ~400-800 bytes)."""
    t = im.copy(); t.thumbnail((20, 20))
    t = t.convert("RGB").filter(ImageFilter.GaussianBlur(0.6))
    buf = io.BytesIO(); t.save(buf, "WEBP", quality=40)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def process(src, key, crop=None, category=CATEGORY):
    """crop = (left, top, right, bottom) as 0..1 fractions of the original."""
    im = Image.open(src).convert("RGB")
    if crop:
        w, h = im.size
        im = im.crop((int(crop[0] * w), int(crop[1] * h),
                      int(crop[2] * w), int(crop[3] * h)))

    outdir = os.path.join(ROOT, "assets", "img", category)
    os.makedirs(outdir, exist_ok=True)

    entries, total = [], 0
    for wid in WIDTHS:
        if entries and wid > im.width * 1.1:
            break                                    # don't upscale
        r = im.copy()
        r.thumbnail((wid, MAX_EDGE), Image.LANCZOS)   # long edge capped here
        name = "%s-%d.webp" % (key, wid)
        path = os.path.join(outdir, name)
        r.save(path, "WEBP", quality=QUALITY, method=6)
        total += os.path.getsize(path)
        entries.append({"w": r.width, "file": "assets/img/%s/%s" % (category, name)})

    return {
        "key": key,
        "src": entries[-1]["file"],
        "srcset": ", ".join("%s %dw" % (e["file"], e["w"]) for e in entries),
        "colour": dominant(im),
        "lqip": lqip(im),
        "ar": round(im.width / im.height, 4),
        "kb": round(total / 1024),
    }


def write_media(records):
    """Emit assets/js/media.js — consumed by app.js, never edited by hand."""
    out = {}
    for r in records:
        out[r["key"]] = {k: r[k] for k in ("src", "srcset", "colour", "lqip", "ar")}
    path = os.path.join(ROOT, "assets", "js", "media.js")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write("/* AUTO-GENERATED by tools/optimize-images.py — do not edit by hand.\n")
        f.write("   Re-run the script after adding photos to tools/originals/. */\n")
        f.write("const MEDIA = ")
        json.dump(out, f, indent=1)
        f.write(";\n")
    return path


def load_existing():
    mpath = os.path.join(ROOT, "assets", "js", "media.js")
    if not os.path.exists(mpath):
        return {}
    m = re.search(r"const MEDIA = (\{.*\});", open(mpath).read(), re.S)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except Exception:
        return {}


def main():
    src_dir = os.path.join(ROOT, "tools", "originals")
    if not os.path.isdir(src_dir):
        os.makedirs(src_dir, exist_ok=True)
        print("Created tools/originals/ — put your photos there and re-run.")
        return

    existing = load_existing()
    records, total = [], 0

    for f in sorted(os.listdir(src_dir)):
        if f.startswith("."):
            continue
        key = re.sub(r"[^a-z0-9]+", "-", os.path.splitext(f)[0].lower()).strip("-")
        try:
            r = process(os.path.join(src_dir, f), key)
            records.append(r); total += r["kb"]
            print("  ok  %-28s %5d KB  %s  ar %.2f" % (key, r["kb"], r["colour"], r["ar"]))
        except Exception as e:
            print("  --  %-28s FAILED: %s" % (key, e))

    for k, v in existing.items():
        if not any(r["key"] == k for r in records):
            v = dict(v); v["key"] = k
            records.append(v)

    p = write_media(records)
    print("\n%d photos processed, %d KB of WebP written." % (len(records), total))
    print("Manifest: %s" % os.path.relpath(p, ROOT))
    print("Keys available to data.js:")
    print("  " + ", ".join(sorted(r["key"] for r in records)))


if __name__ == "__main__":
    main()
